mysql:
    user: root
    password: "123456"
    host: 127.0.0.1
    port: 3306
    db: go
    log_level: dev
    config: ""
logger:
    level: info
    prefix: '[gvb]'
    director: log
    show-line: true
    log_in_console: false
system:
    host: 0.0.0.0
    port: 8080
    env: dev
site_info:
    created_at: "2024-2-9"
    bei_an: 湘ICP备2021010654号-3
    title: xiaoyang_blog
    qq_image: /uploads/file/avatar.png
    version: 6.0.2
    email: 523934596@qq.com
    wechat_image: /uploads/avatar/default.png
    name: xiaoyang
    jog: go开发
    addr: 湖南
    slogan: xiaoyang
    web: https://www.xiaoyang.com
